### ISSUE TITLE
JS error

### ISSUE THREAD

**Issue by moondawg69** [codrops/BackgroundScaleHoverEffect#1]
Hi,

Downloaded the files, fired up index.html and get the preloader and then just hangs.

Console shows: SyntaxError: Unexpected identifier 'Navigation'. import call expects exactly one argument - index.js line 2. 

Browser, latest Safari on OS Catalina but same issue on Firefox etc.

**Comment by piccante** [comment]
Same issue as moondawg69....  Seems the version of the demo deployed on the tympanus.net website includes the following javascript file:
<script src="js.08da537f.js"></script>
Which is 216kB but if you add this to the bottom of the HTML file it works.

**Comment by botelho** [comment]
Hi, did you follow the Installation process? I've done again and I confirm it all works.

**Comment by piccante** [comment]
> Hi, did you follow the Installation process? I've done again and I confirm it all works.

Hi botelho, I did as moondawg did, downloaded the file (zip) but it won't run without that javascript file...

**Comment by botelho** [comment]
I'm not sure how moondawg did. Did you follow the Installation process?
